
if (AB_SDL STREQUAL "1")
  target_include_directories(ab  PRIVATE ${SDL_INCLUDE_DIR})
  target_include_directories(ab  PRIVATE ${SDL_INCLUDE_DIRS})
  # target_link_libraries(ab  PRIVATE SDL::SDL)
  # target_link_libraries(ab  PRIVATE ${SDL_LIBRARIES})
  if (AB_SDL_STATIC)
    if(AB_OS STREQUAL "win32")
      target_link_libraries(ab PRIVATE SDLmain SDL-static)
    else()
      target_link_libraries(ab PRIVATE SDL-static)
    endif()
  else ()
    if(AB_OS STREQUAL "win32")
      target_link_libraries(ab PRIVATE SDLmain SDL)
    else()
      target_link_libraries(ab PRIVATE SDL)
    endif()
  endif ()
  # target_link_directories(ab  PRIVATE ${SDL_LIBRARY_DIRS})
  link_directories(${SDL_LIBRARY_DIRS})
  target_compile_options(ab  PRIVATE ${SDL_CFLAGS_OTHER})
  target_compile_definitions(ab PRIVATE USE_SDL=1)
elseif (AB_SDL STREQUAL "2")
  target_include_directories(ab  PRIVATE ${SDL2_INCLUDE_DIR})
  target_include_directories(ab  PRIVATE ${SDL2_INCLUDE_DIRS})
  # target_link_libraries(ab  PRIVATE SDL2::SDL2)
  # target_link_libraries(ab  PRIVATE ${SDL2_LIBRARIES})
  if (AB_SDL_STATIC)
    if(AB_OS STREQUAL "win32")
      target_link_libraries(ab PRIVATE SDL2main SDL2-static)
    else()
      target_link_libraries(ab PRIVATE SDL2-static)
    endif()
  else ()
    if(AB_OS STREQUAL "win32")
      target_link_libraries(ab PRIVATE SDL2main SDL2)
    else()
      target_link_libraries(ab PRIVATE SDL2)
    endif()
  endif ()
  # target_link_directories(ab  PRIVATE ${SDL2_LIBRARY_DIRS})
  link_directories(${SDL2_LIBRARY_DIRS})
  target_compile_options(ab  PRIVATE ${SDL2_CFLAGS_OTHER})
  target_compile_definitions(ab PRIVATE USE_SDL=2)
elseif (AB_SDL STREQUAL "3")
  target_include_directories(ab  PRIVATE ${SDL3_INCLUDE_DIR})
  target_include_directories(ab  PRIVATE ${SDL3_INCLUDE_DIRS})
  # target_link_libraries(ab  PRIVATE SDL3::SDL3)
  # target_link_libraries(ab  PRIVATE ${SDL3_LIBRARIES})
  if (AB_SDL_STATIC)
    target_link_libraries(ab PRIVATE SDL3-static)
  else ()
    target_link_libraries(ab PRIVATE SDL3)
  endif ()
  # target_link_directories(ab  PRIVATE ${SDL3_LIBRARY_DIRS})
  link_directories(${SDL3_LIBRARY_DIRS})
  target_compile_options(ab  PRIVATE ${SDL3_CFLAGS_OTHER})
  target_compile_definitions(ab PRIVATE USE_SDL=3)
endif ()
